# Ruff configuration for chuk-tool-processor
line-length = 120
target-version = "py311"

[lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "ARG", # flake8-unused-arguments
    "SIM", # flake8-simplify
]
ignore = [
    "E501",  # line too long (handled by formatter)
    "B008",  # do not perform function calls in argument defaults
    "B904",  # raise ... from ... in exception handlers
]

[lint.per-file-ignores]
"tests/**/*" = ["ARG", "S101"]  # Allow unused arguments and asserts in tests
"examples/**/*" = ["ARG"]  # Allow unused arguments in examples

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"